#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-$(CONFIG_MTK_LENS)   += main/
obj-$(CONFIG_MTK_LENS)   += main2/
# main3/ and sub2/ omitted: main3_lens.c / sub2_lens.c are not shipped in the
# SM-A013M open-source release (no AF chip enabled in a01core_defconfig).
obj-$(CONFIG_MTK_LENS)   += sub/